dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^2.15.2"
- name: "grafana"
  condition: grafana.enabled
  version: "~6.43.0"
  repository:  "https://grafana.github.io/helm-charts"
- name: "prometheus"
  condition: prometheus.enabled
  version: "~19.7.2"
  repository:  "https://prometheus-community.github.io/helm-charts"
