dependencies:
- name: "loki"
  condition: loki.enabled
  repository: "https://grafana.github.io/helm-charts"
  version: "^2.15.2"
- name: "grafana"
  condition: grafana.enabled
  version: "~6.43.0"
  repository:  "https://grafana.github.io/helm-charts"
- name: "prometheus"
  condition: prometheus.enabled
  version: "~19.7.2"
  repository:  "https://prometheus-community.github.io/helm-charts"
- name: "jaeger"
  condition: jaeger.enabled
  version: "3.0.10"
  repository: "https://jaegertracing.github.io/helm-charts"
- name: "opensearch"
  condition: "opensearch.enabled"
  version: "2.20.0"
  repository: "https://opensearch-project.github.io/helm-charts/"
- name: "prometheus-elasticsearch-exporter"
  condition: "prometheus-elasticsearch-exporter.enabled"
  version: "5.8.0"
  repository: https://prometheus-community.github.io/helm-charts
- name: "opentelemetry-collector"
  condition: "opentelemetry-collector.enabled"
  version: "0.92.0"
  repository: "https://open-telemetry.github.io/opentelemetry-helm-charts"
- name: "traefik"
  condition: "traefik.enabled"
  version: "28.1.0"
  repository: "https://traefik.github.io/charts"

